### PR TITLE
Auto-uses wormhole during the final moments of the game

### PR DESCRIPTION
**Pull request by GreatOldOne**
Minutes before the end game to start using wormholes is configurable.

### CODE REVIEW

**Comment by GreatOldOne** [comment]
Squashing wasn't enough. It still says there is a conflict.
I'll leave it at that until someone can point what's going on.

**Comment by GreatOldOne** [comment]
Oh right, found it. I'll be squashing a new one.

**Comment by iakat** [comment]
@GreatOldOne please consider not opening a ton of PRs that are gonna be closed minutes after.

**Comment by GreatOldOne** [comment]
I'm sorry, that damn extra " was causing all this trouble.
Was trying to solve it, including booted into my Linux to squash.

**Pull request closed without merging**
