### PR TITLE
Buy upgrades based on their total DPS gain

### PR DESCRIPTION
**Pull request by bschug**
Improvement to auto-upgrades:
Computes actual DPS gain of buying Auto-DPS, Click-Damage, Crit Damage and Elemental Damage. Buys the upgrade with the most DPS gain per cost. Will always buy boss loot if affordable. Buys health upgrades only if health dropped below 50% since the last health upgrade.

### CODE REVIEW

**Comment by rossengeorgiev** [comment]
It already does that all that? Except 50% health buying.

**Comment by bschug** [comment]
No, before it just had a fixed prioritization of Click -> Health -> Auto -> Crit. Now it computes the actual DPS gain of each upgrade and buys the best. Also, I added an option how many hours per day you will be running the script to find the optimal ratio between auto and click damage.

**Comment by rossengeorgiev** [comment]
All these changes are unnecessary. :-1:

**Comment by lsingley** [comment]
It's not necessary to run a script in the first place.  If we're going to use one it should do things the best way possible.  Would be a great addition.

**Comment by rossengeorgiev** [comment]
Current AutoUpgrade already does all this.

**Pull request closed without merging**
