### PR TITLE
Feature: wrap

### PR DESCRIPTION
**Pull request by 1RV34**
I've only done a simple wrap now, after this further optimizations should be easier tho

was looking for functions that might've been called before declaration but eventually realized nothing runs before `firstRun()` and that's ran after declaring of all the functions..

### CODE REVIEW

**Comment by 1RV34** [comment]
during the time of this being merged the config variable won't be accessable but after this has been merged i'll work on putting them to localStorage directly

**Comment by LeoVerto** [comment]
Confirmed to be working.

Can you update this PR to be mergable?

**Comment by 1RV34** [comment]
already working on that, gimme a bit

**Comment by iakat** [comment]
:+1:

**Comment by 1RV34** [comment]
... i did something wrong and i'm not sure what
did i merge in a wrong version....?

**Comment by xPaw** [comment]
rebase your branch, and then you will be able to do the PR correctly.

**Comment by Marlamin** [comment]
image

**Pull request closed without merging**
