### PR TITLE
Prevent clicking when autoclicker is enabled

### PR DESCRIPTION
**Pull request by rossengeorgiev**

### CODE REVIEW

**Comment by iakat** [comment]
I think a function to toggle it would be more useful, as we're going to disable autoclicking in certain situations, such as slow start.

**Comment by iakat** [comment]
:+1:

**Comment by xPaw** [comment]
Use `pointerEvents` instead of `cssText`

**Comment by rossengeorgiev** [comment]
@xPaw if you use the property directly, instead of `cssText`, you can't apply `! important` ok?

**Comment by iakat** [comment]
My bad, this is actually not necessary anymore as of 8158b9ba481563d366da96ff0709939ee8d35b57.

**Pull request closed without merging**
