### PR TITLE
adding dps and gold/sec displays

### PR DESCRIPTION
**Pull request by patsissons**
creating a new PR for this now that it's just the dps and gps displays (in options2). 

feel free to tweak code as needed for style or any other reason.

### CODE REVIEW

**Comment by Contex** [comment]
Perhaps counting the damage done by the auto-fire cannon/etc should be counted towards to total DPS? The DPS you're using in this PR only counts the damage done by the "auto-clicker" (+ multipliers).

**Comment by patsissons** [comment]
yea good point, i'll see if it's easy to sum that in.

**Comment by Contex** [comment]
```
s().m_rgPlayerTechTree.dps
```

Should give you the DPS for the auto-fire turrets if I recall correctly. So 

```
var autoClickerDPS = (damagePerClick * currentClickRate);
var totalDPS = autoClickerDPS + s().m_rgPlayerTechTree.dps;
```

Should give you the total DPS.

**Comment by patsissons** [comment]
ok, seems to work on my end. give it a test

**Comment by xPaw** [comment]
Why aren't you using Valve's FormatNumberForDisplay? Also please avoid using innerHTML.

**Comment by patsissons** [comment]
@xPaw the reason is mostly because i don't do a lot of JS dev. i am competent enough to make it work, but noob enough to not make it "gooder"

**Comment by Contex** [comment]
@patsissons see [example usage of FormatNumberForDisplay](https://github.com/SteamDatabase/steamSummerMinigame/blob/618a5b980e657439f9404be47bfd49abc526c324/autoPlay.user.js#L468), you can get rid of your GetSuffix function this way.
Use textContent/innerText instead of innerHTML if possible.

**Comment by patsissons** [comment]
i'm using innerHTML because i use a &lt;br/> tag to split it up into two lines

**Comment by Contex** [comment]
I'll test it in a bit if nobody else gets the chance.

**Comment by patsissons** [comment]
oops, good catch, meant to remove those lines.

**Comment by patsissons** [comment]
@Contex  fixed and rebased.

**Comment by iakat** [comment]
This isn't necessary anymore.

**Pull request closed without merging**
