### PR TITLE
Nuke high level Bosses

### PR DESCRIPTION
**Pull request by GreatOldOne**
Nuke bosses on high levels, but only if boss health is >= 50% and no
raining gold is active within the lane.

### CODE REVIEW

**Comment by EienSeihai** [comment]
This is for https://github.com/SteamDatabase/steamSummerMinigame/issues/181, yes?

When he said raining gold level, he meant every level that was divisible by 200 (maybe 100? check code), not just if raining gold was currently active in the lane. The script auto uses raining gold on levels over 1k that are divisible by 200 (or 100, or something).

**Comment by GreatOldOne** [comment]
This was his ISSUE:

Use nuke on bosses on high levels (if not raining gold level)

And that's exactly what I've implemented.
Nuking the boss if raining gold is active looks like a waste, even on high levels.

**Comment by EienSeihai** [comment]
No, yours just checks if raining gold is active, not if the level is determined to be a raining gold level by the script (which is every 200/250 levels).

Your implementation will not use a nuke when any non scripter activates raining gold, which is almost every boss level. Don't check if there's raining gold active but instead check if the level number is divisible by 200 or 250.

**Comment by GreatOldOne** [comment]
It can still activate the nuke, once raining gold ceases. Which happens quite frequently, as long as the boss is higher than 50% HP.

**Comment by GreatOldOne** [comment]
This is the code for raining gold:

```
// Gold Rain
if (canUseAbility(ABILITIES.RAINING_GOLD)) {

    enemy = s().GetEnemy(s().m_rgPlayerData.current_lane, s().m_rgPlayerData.target);
    // check if current target is a boss, otherwise its not worth using the gold rain
    if (enemy && enemy.m_data.type == ENEMY_TYPE.BOSS) {
        enemyBossHealthPercent = enemy.m_flDisplayedHP / enemy.m_data.max_hp;

        if (enemyBossHealthPercent >= 0.6) { // We want sufficient time for the gold rain to be applicable
            // Gold Rain is purchased, cooled down, and needed. Trigger it.
            advLog('Gold rain is purchased and cooled down, Triggering it on boss', 2);
            triggerAbility(ABILITIES.RAINING_GOLD);
        }
    }
}
```

There is no raining gold level,

**Comment by iakat** [comment]
There is going to be gold rain level as soon as it's implemented, so yes, please do check for it.

**Comment by GreatOldOne** [comment]
How about we continue to avoid nuking bosses if raining gold is active and prevent any nuking at all on raining gold levels?
I still think it's a waste to nuke a boss when raining gold is active.

**Comment by GreatOldOne** [comment]
I need an answer for this one asap before I can start working on my end game logic for today (including  always nuking bosses at the end).

**Comment by Contex** [comment]
Thoughts? @chauffer && @xPaw (related to #181)

**Comment by xPaw** [comment]
:+1:

**Comment by GreatOldOne** [comment]
Alright, can this be merged? I'll submit a patch as soon as this is merged to add no nuking on raining gold levels (my repo is way behind this one and I need to update it before I start working on other things).

**Comment by xPaw** [comment]
@GreatOldOne this patch is fine, but you need to rebase it.

**Comment by GreatOldOne** [comment]
@xPaw Why? I haven't submitted anything else to this patch.

**Comment by xPaw** [comment]
Because there were changes to master, and this PR is based on an older commit and can't be merged automatically.

**Comment by GreatOldOne** [comment]
I think this merge caused the conflict https://github.com/SteamDatabase/steamSummerMinigame/pull/216
It took so long for this simple patch to be merged that I won't have time to rebase it right now (maybe by my night time GMT-3).
If someone wants to do that for me, I would appreciate it.

**Pull request closed without merging**
