### PR TITLE
Cahnge all `level % 500 === 0` to isWormholeRound

### PR DESCRIPTION
**Pull request by MatthewClair**
Closes SteamDatabase/steamSummerMinigame#266

### CODE REVIEW

**Comment by xPaw** [comment]
It's confusing because isWormholeRound used in the last game hour, so different logic.

**Comment by MatthewClair** [comment]
I'm not sure what you mean.  If it is supposed to use the same modulo,
using one function for all of it is the simplest and safest way.

**Comment by xPaw** [comment]
The problem is that it's not supposed to be the same. Every 100 rounds in last hour, every 500 otherwise.

**Comment by MatthewClair** [comment]
Ah, then I think the function should be updated to reflect that since it
isn't clear that is the intent.

**Comment by xPaw** [comment]
df940a003292c6121346ab19c29bcf77c8b0b1ab

**Pull request closed without merging**
