### PR TITLE
Added hint to explain why elementals are disabled. Checkbox moved close to elements.

### PR DESCRIPTION
**Pull request by zgeal2**
Issue 20: https://github.com/SteamDatabase/steamSummerMinigame/issues/20

### CODE REVIEW

**Comment by iakat** [comment]
You remove the option to lock elements. Please undo that, also, rebase to the latest version.

**Comment by zgeal2** [comment]
It wasn't removed. It was moved to the Elements. Hint is appearing while you hovering mouse above it.
scr

**Comment by xPaw** [comment]
You need to rebase your branch.

**Comment by xPaw** [comment]
You didn't rebase it, you made it worse. See this: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by zgeal2** [comment]
Yea, i'll do rebase Head~2, delete previous commit and rebase to your branch. Just need a git client.

**Comment by zgeal2** [comment]
FInaly. Thank you Lord for git reset --hard HEAD
Sorry for stupidity.

**Pull request closed without merging**
