### PR TITLE
Restyling some items

### PR DESCRIPTION
**Pull request by HxxxxxS**
Before:
Before

After:
After

### CODE REVIEW

**Comment by xPaw** [comment]
Looks fine to me

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Ok, but then also add the "Lock Element Box" option on bottom to the other Options, so that its still available.

**Comment by xPaw** [comment]
It's still there, left from your health actually.

**Comment by HxxxxxS** [comment]
I thought it was placed near the elements to remove confusion as to why
elements were disabled. Could easily just move it to settings though

man. 15. jun. 2015 kl. 10.05 skrev K4r0qtuYNE5G4qgZ <
notifications@github.com>:

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Ok, not seen it. Yeah, its just perfect there, so the empty Place is used well.

**Pull request merged**
