### PR TITLE
(fixed pull) Removed Cooldown / Added Cooldown Handler to Nuke, Napalm, Clusterbomb. Closes #197

### LINKED ISSUE #197: Decrease Cooldown is wasted for nothing and even disabled after its used once
This Ability should only be used before spamming other Abilities with a large Cooldown OR if there are a lot of Abilities used in Lane with large Cooldown or look my other Issue on that Topic if alot of Abilities  was used where the Cooldown is already running.

Also don't lock it after using it once, anyway why it gets disabled once used?

Here a Snippet of another Script that looks more promising for the Cooldown use

```
function useClusterBombIfRelevant() {
    //Check if Cluster Bomb is purchased and cooled down
    if (hasPurchasedAbility(ABILITIES.CLUSTER_BOMB)) {
        if (isAbilityCoolingDown(ABILITIES.CLUSTER_BOMB)) {
            return;
        }
        //Check lane has monsters to explode
        var currentLane = g_Minigame.CurrentScene().m_nExpectedLane;
        var enemyCount = 0;
        var enemySpawnerExists = false;
        //Count each slot in lane
        for (var i = 0; i < 4; i++) {
            var enemy = g_Minigame.CurrentScene().GetEnemy(currentLane, i);
            if (enemy) {
                enemyCount++;
                if (enemy.m_data.type == 0) { 
                    enemySpawnerExists = true;
                }
            }
        }
        //Bombs away if spawner and 2+ other monsters
        if (enemySpawnerExists && enemyCount >= 3) {
            // Wait 60 seconds if the cooldown ability
            // is within 1 minute of coming back
            if (getCooldownTime(ABILITIES.COOLDOWN) > 60 || !hasPurchasedAbility(ABILITIES.COOLDOWN) || (hasPurchasedAbility(ABILITIES.COOLDOWN) && !isAbilityCoolingDown(ABILITIES.COOLDOWN))) {
                if (hasPurchasedAbility(ABILITIES.COOLDOWN) && !isAbilityCoolingDown(ABILITIES.COOLDOWN) && !currentLaneHasAbility(ABILITIES.COOLDOWN)) {
                    console.log("Cooling down prior to long-downtime ability use");
                    triggerAbility(ABILITIES.COOLDOWN);
                } else {
                    triggerAbility(ABILITIES.CLUSTER_BOMB);
                }
            }
        }
    }
}
```

Add that also to Nuke and Clusterbomb too...

Or check them in another Function and triggerAbility(ABILITIES.COOLDOWN); there.

Because the actual use of Cooldown is bugged, or what does this actual do?

```
    // Cooldown
    if(getActiveAbilityLaneCount(ABILITIES.DECREASE_COOLDOWNS) > 0) {
        disableAbility(ABILITIES.DECREASE_COOLDOWNS);
    }
    else
    {
        if(!s().bIsAbilityActive(ABILITIES.DECREASE_COOLDOWNS)) {
            enableAbility(ABILITIES.DECREASE_COOLDOWNS);
        }

        tryUsingAbility(ABILITIES.DECREASE_COOLDOWNS);
    }
```

Use it and lock it? Why? For what?

This only works if the Abilities are used and currently active in Lane, only then it does actually reduce the Cooldown by 10 Minutes, so only use it when at least one is active and actually in cooldown Phase OR use it just before using a such one...

Why not use something like that instead

```
    // Cooldown
    if(canUseAbility(ABILITIES.COOLDOWN))
    {
        var nuke = (getActiveAbilityLaneCount(ABILITIES.TACTICAL_NUKE) > 0);
        var napalm = (getActiveAbilityLaneCount(ABILITIES.NAPALM) > 0);
        var clusterbomb = (getActiveAbilityLaneCount(ABILITIES.CLUSTER_BOMB) > 0);
        var cooldown = (getActiveAbilityLaneCount(ABILITIES.COOLDOWN) > 0); // Yeah, because Cooldown itself gets also cooldown too if active    
        var totalRelevantAbilities = nuke + napalm + clusterbomb + cooldown;

        if (totalRelevantAbilities >= 2) // Can be tweaked also like only if more are active together
        {
            triggerAbility(ABILITIES.COOLDOWN);
        }    
    }
```

Typed that myself, dunno if works, will test... ;)

### PR DESCRIPTION
**Pull request by K4r0qtuYNE5G4qgZ**
Hope everyone is happy now...

Also i allready tested it, it runs for several Hours with it and works very well

### CODE REVIEW

**Comment by xPaw** [comment]
So what's the logic behind this change? It will trigger these abilities if it can't do cooldown first?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
First the existing Cooldown Function was totally broken, it triggers it once and the disable the Ability, so useless and removed.

My Change assures that if Cooldown is available it triggers Cooldown 1 second before and then the Ability, which then benefits from Cooldown.

If Cooldown isn't available it simply triggers the Abilility.

It works because (!tryUsingAbility(ABILITIES.DECREASE_COOLDOWNS)) actually triggers the Cooldown if available and returns true and then on the next Tick one second later the Ability will trigger because it will return false. Easy and Clean isn't it? ;)

Also if someone else already activated a Cooldown and you trigger your, then your Cooldown itself benefits from the other Cooldown too because its a Ability that was activated while a Cooldown is active, so win-win somehow if that happens.

**Comment by xPaw** [comment]
Yeah it looks like a fine solution to me. @chauffer?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Also it seems even to have the Sideeffect of distribute the Ability use a bit because if Nuke if activated it will benefit of Cooldown and shifted ~10mins and the same for the others if they are not activated all together they will shift slowly because some benefits from cooldown while other not.

But of course it doesn't entirely solve the "Too many abilities being used simultaneously." Issue, so for that another fix is needed. But for Nuke, Napalm, Clusterbombs it seems to distribute the use a bit over Time.

**Pull request merged**
