### PR TITLE
Remove lower upgrades

### PR DESCRIPTION
**Pull request by luanmuniz**
This is a try to solve #105 
Its easy to understand and we can implement an auto-buy over it very easy

### CODE REVIEW

**Comment by rossengeorgiev** [comment]
This is stupid since eventually lower tier upgrades are more cost effective than upper tier.

**Comment by luanmuniz** [comment]
@rossengeorgiev Can you point what are those cases? Its easy to modify this script to support this kind of verification. Because you need 10 upgrades of a lower to be cheap than an upgrade for this be true.

By the way, there is a discussion about this in #105

**Comment by luanmuniz** [comment]
Let me try to fix the build first. After that i will try to build a function that check if that can be true

**Comment by rossengeorgiev** [comment]
See #143

**Comment by iakat** [comment]
#143 is a better approach to this as lower level ones can be more cost-effective.

**Pull request closed without merging**
