### PR TITLE
Auto use Treasure if player gold is less than 100k

### PR DESCRIPTION
**Pull request by Xinayder**
I was thinking about setting the activation limit to `100000 * s().m_rgGameData.level`.

### CODE REVIEW

**Comment by xPaw** [comment]
Yeah, the check definitely should be something different than 100k.

**Comment by Xinayder** [comment]
Setting it to what I suggested above triggers the treasure everytime. However, I don't think that's an issue.

**Comment by wchill** [comment]
My recommendation is just using all of it at game start and when you get it. After that, 100k is nothing.

**Comment by iakat** [comment]
Is this of any use right now?
You can just use it yourself if you need gold, the script does not (yet) automate anything economically.

**Comment by iakat** [comment]
We should also consider not wasting it and using it as a metal detector when the boss is close to death.

**Comment by Xinayder** [comment]
@chauffer what happens when someone like me has ~200x treasure items? hehe.
edit: good idea. editing my commit.

**Comment by HxxxxxS** [comment]
for the first X amount of levels it should probably be used whenever off cooldown. After that I suggest doing as @chauffer suggested right above

**Pull request merged**
