### PR TITLE
AutoUpgrade: auto purchase of badges (WH priority)

### PR DESCRIPTION
**Pull request by rossengeorgiev**
Tested seems to work

Related: #215 #254

### CODE REVIEW

**Comment by xPaw** [comment]
It should also buy Like New.

**Comment by rossengeorgiev** [comment]
@xPaw how many tho?

**Comment by rossengeorgiev** [comment]
Ok, this has a bug.

**Comment by rossengeorgiev** [comment]
This looks good. YOLO

**Pull request merged**
