### PR TITLE
Show all active abilities option

### PR DESCRIPTION
**Pull request by albert--**
sets height of #activeinlanecontainer to auto

### CODE REVIEW

**Comment by GreatOldOne** [comment]
Any reason this PR hasn't been merged yet?

**Comment by xPaw** [comment]
Because it looks very bad, and keeps jumping around.

**Comment by Ditti4** [comment]
Well, better than hiding some of the abilities, isn't it?

**Comment by GreatOldOne** [comment]
Maybe change the size to a static one instead of auto. The number of acivated abilities is limited, so we don't need to keep resizing it later.

**Comment by albert--** [comment]
27 possible abilities
5 abilities per row
27/5 = 5.4
6 rows to show every possible ability
~62px per row

fixed one would be around 372px which is way too big (http://i.imgur.com/hmV6W6x.png)

**Comment by GreatOldOne** [comment]
You need to resize the box aswell. It's not an image, just CSS.

**Pull request closed without merging**
