### PR TITLE
Added option to nuke abilities before game end

### PR DESCRIPTION
**Pull request by Xinayder**
I say :shipit:. @chauffer, @xPaw?

### CODE REVIEW

**Comment by GreatOldOne** [comment]
Don't like it.
I like to set mine to 30 or 20 minutes, depending on how many wormholes I've.

**Comment by GreatOldOne** [comment]
That was a bad merge in my opinion.
If I only have a few wormholes left, I want to set exactly when I want to use them (and as close to the end as possible).
Meh.

**Comment by GreatOldOne** [comment]
Besides, this doesn't need to be a toggleable option.
The items will be lost after the game resets, and anyone can just set it to 5 minutes before the game ends.

I think i'll be forking a branch just to replace this change.

**Comment by Xinayder** [comment]
@GreatOldOne if you want to use your wormholes whenever you want to, just disable the option and use them ;)

**Comment by GreatOldOne** [comment]
Then I need to use them manually and have to check the lane myself to see if someone has done it already.

**Comment by GreatOldOne** [comment]
I did set mine to 20 mins today, with 10 wormholes and I sitll got like 8 minutes before the game ended.

**Comment by pcki11** [comment]
maybe the amount of time before reset should be decided based on the amount of wormholes a player has? if he has more than 60 wormholes, this change means he would lose some (1min cooldown).

**Comment by GreatOldOne** [comment]
But there are other factors, like throw money after wormholes are exhausted and in the future we could add more options for isNearEndGame().

**Comment by squee666** [comment]
@GreatOldOne Wormholes do stack you know. so it doesnt matter how many per lane are used

**Comment by iakat** [comment]
Please continue this in #190.

**Pull request merged**
