### PR TITLE
Removed Cooldown / Added Cooldown Handler to Nuke, Napalm, Clusterbomb. Closes #197

### LINKED ISSUE #197: Decrease Cooldown is wasted for nothing and even disabled after its used once
This Ability should only be used before spamming other Abilities with a large Cooldown OR if there are a lot of Abilities used in Lane with large Cooldown or look my other Issue on that Topic if alot of Abilities  was used where the Cooldown is already running.

Also don't lock it after using it once, anyway why it gets disabled once used?

Here a Snippet of another Script that looks more promising for the Cooldown use

```
function useClusterBombIfRelevant() {
    //Check if Cluster Bomb is purchased and cooled down
    if (hasPurchasedAbility(ABILITIES.CLUSTER_BOMB)) {
        if (isAbilityCoolingDown(ABILITIES.CLUSTER_BOMB)) {
            return;
        }
        //Check lane has monsters to explode
        var currentLane = g_Minigame.CurrentScene().m_nExpectedLane;
        var enemyCount = 0;
        var enemySpawnerExists = false;
        //Count each slot in lane
        for (var i = 0; i < 4; i++) {
            var enemy = g_Minigame.CurrentScene().GetEnemy(currentLane, i);
            if (enemy) {
                enemyCount++;
                if (enemy.m_data.type == 0) { 
                    enemySpawnerExists = true;
                }
            }
        }
        //Bombs away if spawner and 2+ other monsters
        if (enemySpawnerExists && enemyCount >= 3) {
            // Wait 60 seconds if the cooldown ability
            // is within 1 minute of coming back
            if (getCooldownTime(ABILITIES.COOLDOWN) > 60 || !hasPurchasedAbility(ABILITIES.COOLDOWN) || (hasPurchasedAbility(ABILITIES.COOLDOWN) && !isAbilityCoolingDown(ABILITIES.COOLDOWN))) {
                if (hasPurchasedAbility(ABILITIES.COOLDOWN) && !isAbilityCoolingDown(ABILITIES.COOLDOWN) && !currentLaneHasAbility(ABILITIES.COOLDOWN)) {
                    console.log("Cooling down prior to long-downtime ability use");
                    triggerAbility(ABILITIES.COOLDOWN);
                } else {
                    triggerAbility(ABILITIES.CLUSTER_BOMB);
                }
            }
        }
    }
}
```

Add that also to Nuke and Clusterbomb too...

Or check them in another Function and triggerAbility(ABILITIES.COOLDOWN); there.

Because the actual use of Cooldown is bugged, or what does this actual do?

```
    // Cooldown
    if(getActiveAbilityLaneCount(ABILITIES.DECREASE_COOLDOWNS) > 0) {
        disableAbility(ABILITIES.DECREASE_COOLDOWNS);
    }
    else
    {
        if(!s().bIsAbilityActive(ABILITIES.DECREASE_COOLDOWNS)) {
            enableAbility(ABILITIES.DECREASE_COOLDOWNS);
        }

        tryUsingAbility(ABILITIES.DECREASE_COOLDOWNS);
    }
```

Use it and lock it? Why? For what?

This only works if the Abilities are used and currently active in Lane, only then it does actually reduce the Cooldown by 10 Minutes, so only use it when at least one is active and actually in cooldown Phase OR use it just before using a such one...

Why not use something like that instead

```
    // Cooldown
    if(canUseAbility(ABILITIES.COOLDOWN))
    {
        var nuke = (getActiveAbilityLaneCount(ABILITIES.TACTICAL_NUKE) > 0);
        var napalm = (getActiveAbilityLaneCount(ABILITIES.NAPALM) > 0);
        var clusterbomb = (getActiveAbilityLaneCount(ABILITIES.CLUSTER_BOMB) > 0);
        var cooldown = (getActiveAbilityLaneCount(ABILITIES.COOLDOWN) > 0); // Yeah, because Cooldown itself gets also cooldown too if active    
        var totalRelevantAbilities = nuke + napalm + clusterbomb + cooldown;

        if (totalRelevantAbilities >= 2) // Can be tweaked also like only if more are active together
        {
            triggerAbility(ABILITIES.COOLDOWN);
        }    
    }
```

Typed that myself, dunno if works, will test... ;)

### PR DESCRIPTION
**Pull request by K4r0qtuYNE5G4qgZ**
- Completely removed the currently non working and bugged separate Cooldown Potion
- Added Cooldown Handling before Nuke, Napalm, Clusterbomb

Tested and works perfectly!

### CODE REVIEW

**Comment by iakat** [comment]
I don't get it, are you only using bombs when cooldown is _not_ activable, and never activating it anyway?

**Comment by K4r0qtuYNE5G4qgZ** [comment]
No, it works perfectly like this, i tested it, it's the most elegant Method... ;)

It assures that if Cooldown is available it triggers Cooldown 1 second before and then the Ability, which then benefits from Cooldown.

If Cooldown isn't available it simply triggers the Abilility.

It works because (!tryUsingAbility(ABILITIES.DECREASE_COOLDOWNS)) actually triggers the Cooldown if available and returns true and then on the next Tick one second later the Ability will trigger because it will return false. Easy and Clean isn't it? ;)

Also if someone else already activated a Cooldown and you trigger your, then your Cooldown itself benefits from the other Cooldown too because its a Ability that was activated while a Cooldown is active, so win-win somehow if that happens.

**Comment by iakat** [comment]
Please change the spaces to tabs and squash your commits once done.

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Ok, will try i also made a mistake, one is wrong, is on Cripple Monster instead of Bomb...

Will try to do a new pull...

EDIT: no its correct on my Side, but somehow the pull was changed, everything moved?

Ahh no it only collapsed the Lines, well that's really confusing...

Btw. What do you mean with squash commits?

**Comment by wchill** [comment]
When he says squash commits, he means run `git rebase -i` on your branch.

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Hmm, ok, but i only use the Webinterface and have no access to Serverconsole, so i don't get it how i should do that? Or is that related to that additional Github App that can be run locally? I never used it... LOL!

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I'm sorry but i don't get it.

I installed that Github App and cloned the fork and entered git rebase -i but nothing happens, all i get is

Successfully rebased and updated refs/head/master

I done it 10 Times now...

Thats all, nothing happens, nothing changed, also why the Webinterface has no Button for that, silly...

Someone else suggested to do git push -f, i done it, nothing happens, nothing changes...

And syncing says everything synced...

I somehow suppose this simply don't work in that case...

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Ok forget it, that rebase -i thing does nothing and while desperately trying everything others mentioned now everything is messed up...

So i will simply delete the Fork and Refork, seems to be how Github work, deleting and refork, deleting and refork, deleting and refork because webinterface does not provide any useable Things else...

Would have been better to simply apply the two simple commits instead, but whatever i delete now, it annoys me... Also the best Error i got was "cannot merge because it's unmerged" nice one, its like cannot delete because its not deleted, silly github...

**Comment by K4r0qtuYNE5G4qgZ** [comment]
deleted, reforked, repulled...

**Pull request closed without merging**
