### PR TITLE
Added indicator for most cost effective upgrade

### PR DESCRIPTION
**Pull request by rossengeorgiev**
a
b

### CODE REVIEW

**Comment by iakat** [comment]
Change the color from yellow to red, maybe, we could add some explaination about this, too.
@xPaw

**Comment by rossengeorgiev** [comment]
Red would be too much, color is fine. Perhaps, add toggle for this, which would also explain what it does.

**Comment by xPaw** [comment]
There's no need for a toggle, just a simple note somewhere would do.

**Comment by rossengeorgiev** [comment]
@xPaw should work on chrome now

**Comment by ghost** [comment]
I think changing the color of the upgrade's background would look better than changing the color of the name.

**Comment by ryantheleach** [comment]
Agree'd yellow text is far too subtle.

**Comment by luanmuniz** [comment]
By Reading the code, it does not look like this code take in consideration that the price of 10 lvl 1 upgrades need to be cheap than 1 lvl 2 upgrade for that to be "better".

Is there a function in the core of `s()` that calculate this?

**Comment by rossengeorgiev** [comment]
@luanmuniz if that's your conclusion then you are reading the code wrong

**Comment by HxxxxxS** [comment]
is the price increase taken into account at all? 10x tier 2 upgrades does
not cost the same as 1x tier 3 upgrade

**Pull request closed without merging**
