### PR TITLE
Updates to AutoUpgrade

### PR DESCRIPTION
**Pull request by rossengeorgiev**
- Changed some code around
- Added HP auto upgrading, which stops once you have over 500k HP.
- Upgrade targets are now highlighted in the upgrade list; #161

### CODE REVIEW

**Comment by xPaw** [comment]
I ended up with 112M health with autobuy.

**Comment by Contex** [comment]
Ended up at 112M as well.
@rossengeorgiev var upg_enabled (which sets the limit) is never used in your code.

**Comment by rossengeorgiev** [comment]
@Contex you are right, I've missed that while rearranging the code. 

@xPaw fixed now

**Comment by rossengeorgiev** [comment]
Added prioritization of click upgrades over DPS. Not tested yet, waiting for game 300/1000 :-1: 

Related to #192 #194

**Comment by iakat** [comment]
@rossengeorgiev Did you test this?

**Comment by iakat** [comment]
>  lz1dev │ just not the click prioritization  
>  lz1dev │ but it probably works

**Pull request merged**
