### PR TITLE
Improve title info

### PR DESCRIPTION
**Pull request by iakat**

### CODE REVIEW

**Comment by Xinayder** [comment]
Does it display how many minutes/hours/seconds before the game ends?

Could be achieved by using `g_Minigame.m_CurrentScene.m_rgGameData.timestamp_game_start` if it does not do what I've said above.

**Comment by GreatOldOne** [comment]
timestamp_game_start is not a good data to use for that, since a game can start after 16 GMT.
Checking the system's date for the next 16 GMT is the right approach.

**Comment by Xinayder** [comment]
@GreatOldOne I don't understand it... It will check against the timestamp of 4 PM GMT from tomorrow.

**Comment by GreatOldOne** [comment]
isn't g_Minigame.m_CurrentScene.m_rgGameData.timestamp_game_start the time that specific game room started?

**Comment by Xinayder** [comment]
Oh, I got it now. You're right :smile:

**Pull request closed without merging**
