### PR TITLE
adding click rate editing and dps and gold/sec displays. also moving default click rate to 20

### PR DESCRIPTION
**Pull request by patsissons**
numeric up down for click rate editing.

dps and gold displays update automatically.

### CODE REVIEW

**Comment by Contex** [comment]
I'd make use of the window.FormatNumberForDisplay = function(num, digits) method from ui.js

**Comment by patsissons** [comment]
yea i should mention that i hacked this together really fast. I'm sure one of the regular contributors could clean this up a make it look much better than my code.

**Comment by johndrinkwater** [comment]
We’re not going to accept a patch to edit clickRate or change the current default. If you want to break out the other changes, feel free to make another PR :)

**Comment by patsissons** [comment]
probably not unless someone comments here that they want it. I was mostly just contributing the mods I did in case someone was interested in doing the same thing (and at the time there were some issues around click rate).

**Pull request closed without merging**
