### PR TITLE
replace (needs reload) with an asterisk

### PR DESCRIPTION
**Pull request by HxxxxxS**
as requested in #78

### CODE REVIEW

**Comment by HxxxxxS** [comment]
now without reindenting all the tabs with spaces

**Comment by xPaw** [comment]
Use style.color directly to set color

**Comment by HxxxxxS** [comment]
ah, yeah, shit, i did that first, but i changed it because of a syntax error but i can swap it back again

**Comment by xPaw** [comment]
It's kinda hard to see these astericks. Perhaps try messing with size/brighter color?

**Comment by HxxxxxS** [comment]
I tried using the #a33100 from the healthbar, but #e1b21e from the money indicator might be better

**Comment by xPaw** [comment]
#FF5252 looks better, but I think it still needs to be increased in size.

**Comment by xPaw** [comment]
@hansskogvold Can you rebase/change color? Then I will merge it.

**Comment by HxxxxxS** [comment]
Done. There is a conflict on line 161 now though.

**Comment by xPaw** [comment]
Can you rebase and resolve that conflict?

**Comment by HxxxxxS** [comment]
there we go...i think? :stuck_out_tongue:

**Comment by xPaw** [comment]
Cool! Could you squash your changes now?

**Comment by xPaw** [comment]
Oh yea, you missed one option now, "Enable targeting pointer"

**Comment by xPaw** [comment]
Squash your changes please, and I will merge it.

**Comment by xPaw** [comment]
@hansskogvold are you able to do that?

**Comment by HxxxxxS** [comment]
no, I can't actually, it will have to wait to tomorrow

**Pull request closed without merging**
