### PR TITLE
Add automatic upgrade purchasing functionality

### PR DESCRIPTION
**Pull request by NotTsunami**
Credits to @russeli and @gapple

### CODE REVIEW

**Comment by NotTsunami** [comment]
@russeli I removed the empty ifs and brought it to date, can you double check to make sure everything is good?

**Comment by johndrinkwater** [comment]
“The Travis CI build failed” some fixes required for this.

**Comment by NotTsunami** [comment]
Yeah, I saw that. It's that way on the other autobuy pr at the moment too, going to double check now.

**Comment by russeli** [comment]
@Tsunamical Everything seems good.

**Comment by Tsunamical** [comment]
How can I fix up the last undefined jshint error ('g_Minigame' is not defined)? Also, going to squish into one nice commit after it's ready.

**Comment by russeli** [comment]
I think you could've replaced g_Minigame.CurrentScene() with s() instead.

**Comment by Xinayder** [comment]
You should make it so it only purchases the basic cannon/click/health upgrades 10 times, then it switches to tier 2, tier 3 and then tier 4.

Also, `git commit --amend` is your friend :)

**Comment by NotTsunami** [comment]
Swapping out for s() now. Good to go otherwise. Gonna squish and open a new pr. I'll work on Rocky's suggestion for a later pr unless you want to jump on it @russeli

**Comment by russeli** [comment]
But why should it do that when sometimes for example 10 Auto-fire Cannons are better than 1 Advanced Targeting

**Comment by iakat** [comment]
Definitely what @RockyTV said, make it 10 per each tier.

**Comment by NotTsunami** [comment]
Alright, closing now.

**Comment by iakat** [comment]
Oh. :crying_cat_face:

**Comment by NotTsunami** [comment]
Gonna reopen as a new one and squish the commits. Really ugly lol

**Comment by russeli** [comment]
Would someone mind elaborating for me why do we want 10 per tier? You sometimes do get more bang for the buck with lower tier upgrades.

**Comment by jimmydorry** [comment]
Because people are silly. These same kinds of people advocate specialising in an element, so we can get more unreliable damage.

**Comment by NotTsunami** [comment]
@russeli But it should still buy the higher tier one when it's more cost effective as the script is right now, right?

**Comment by russeli** [comment]
It does buy the most cost efficient upgrade.

**Comment by Xinayder** [comment]
Uh, I don't think that buying low tier upgrades is more effective than buying high tier.

There comes a time where low tier upgrades cost the same as a high tier one, and do little difference (such as Light Armor late game, it costs billions and increases 100(needs confirmation) in your health.

**Comment by NotTsunami** [comment]
Okay, then we should definitely leave it as it is imo. #124 is the latest up to date pr.

**Pull request closed without merging**
