### PR TITLE
Added Autobuy

### PR DESCRIPTION
**Pull request by sithrebel15**
Autobuy by @russeli

### CODE REVIEW

**Comment by russeli** [comment]
Not that this does not purchase elemental damage, critical damage or boss loot upgrades or any abilities.  
Few adjustements should be made if used with autoclicker. Either assigning `currentClickRate` to `avgClicksPerSecond` or replacing `avgClicksPerSecond` with it should be sufficient.  
Also it seems like this is not the latest version, so there's atleast one bug. :)

**Comment by sithrebel15** [comment]
@russeli could you direct me to the latest version please. It looks the same as the one in your fork.

**Comment by NotTsunami** [comment]
I believe @russeli meant don't assign currentClickRate a value, though I could be mistaken.

**Comment by russeli** [comment]
@DarkLordJack russeli/steamSummerMinigame@f45853863af148eff9069d9d4554f250f3a3afc2  
@Tsunamical In purchaseUpgrades function there's variable called `avgClicksPerSecond` that is used to calculating which upgrade is the best. For now I have set it to 3, but when merged into this repo, it's value should be set to be same as `currentClickRate`

**Comment by NotTsunami** [comment]
@russeli He actually tossed that commit in the replace avgClicksPerSecond with currentClickRate commit (https://github.com/DarkLordJack/steamSummerMinigame/commit/60ed48396ba83473bafd92f7a50b9859fd27f8db).

And also, so instead of setting 3, we should just leave it then, like this?: https://github.com/Tsunamical/steamSummerMinigame/commit/e0928c8917fb54188b9a7358b0b4b7db725a936a

**Comment by russeli** [comment]
@Tsunamical Yes, like that.

**Comment by Xinayder** [comment]
You should make it so it only purchases the basic cannon/click/health upgrades 10 times, then it switches to tier 2, tier 3 and then tier 4.

**Comment by sithrebel15** [comment]
Its designed to buy the most cost effective upgrade. It just got merged
into the upstream a few minutes ago.

**Comment by sithrebel15** [comment]
SteamDatabase/steamSummerMinigame/pull/124

**Pull request closed without merging**
